# -*- coding: utf-8 -*-
"""Task_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzUtGwfQioZg-aAiPGBcA4N_xR02Nb5c

#Prime Number Checker
"""

def prime_checker(n):
    if n <= 1:
        print(f"{n} is not prime")
    elif n == 2:
        print(f"{n} is prime")
    elif n % 2 == 0:
        print(f"{n} is not prime")
    else:
        for i in range(3, int(n ** 0.5) + 1, 2):      #chat GBT
            if n % i == 0:
                print(f"{n} is not prime")
                return
        print(f"{n} is prime")
print(prime_checker(1))