# -*- coding: utf-8 -*-
"""Task_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2pCFq74HvWyB8eryaFsnCfTGK1YLC5i

#Custom Calculator
"""

def calculator(a, b, operation):
    if operation == "add":
        return a + b
    elif operation == "subtract":
        return a - b
    elif operation == "multiply":
        return a * b
    elif operation == "divide":
        if b != 0:
            return a / b
        else:
            return "Error: Cannot divide by zero"
    else:
        return "Error: Invalid operation"
print(calculator(1, 2, "add"))